-- WAY (Where Are You) - migration 0002: users-as-devices consolidation + settings
-- Run with:
--   wrangler d1 execute way-db --remote --file=migrations/0002_settings.sql
--
-- Big model change from 0001: there is no longer a separate `devices`
-- table. One person == one tracked entity; the person's dashboard login
-- (username/password) is ALSO their μlogger upload credential, and the
-- `device_id` written into gps_pings/messages is simply the username.
-- This is why the seeded `devices` rows (MaxX/Niri) are dropped below --
-- create the real people as users instead.

-- ============================================================
--  users: add per-user settings columns
-- ============================================================
ALTER TABLE users ADD COLUMN follow_zoom INTEGER NOT NULL DEFAULT 16;
ALTER TABLE users ADD COLUMN home_fence TEXT; -- geofence name for the map's "home" view; NULL = default center

-- ============================================================
--  invite_codes: replaces the single INVITE_CODE secret. 6-digit numeric,
--  single-use, 30-minute expiry. Generated by an admin, consumed by signup.
-- ============================================================
CREATE TABLE invite_codes (
  id         INTEGER PRIMARY KEY AUTOINCREMENT,
  code       TEXT NOT NULL UNIQUE,
  created_by INTEGER REFERENCES users(id),
  created_at TEXT DEFAULT CURRENT_TIMESTAMP,
  expires_at TEXT NOT NULL,
  used_by    INTEGER REFERENCES users(id),
  used_at    TEXT
);

-- ============================================================
--  devices: dropped. gps_pings.device_id and messages.device_id now hold
--  usernames.
--
--  !! The "inert and harmless" reasoning that used to sit here was WRONG, and
--  !! this drop silently broke the chat flush for weeks. `messages` keeps its
--  !! REFERENCES devices(device_id) from 0001; in D1 the FK parent is resolved
--  !! when the statement is PREPARED, so with `devices` gone every insert the
--  !! flush makes into `messages` fails ("no such table: main.devices"), the
--  !! flush aborts, chat history freezes and unsynced rows pile up in the
--  !! Durable Object -- while the live chat keeps working, so nothing looks
--  !! wrong in the UI.
--
--  The SQL above stays exactly as it ran (migrations are history). Any
--  database built from this history needs
--  `scripts/repair-way-messages-fk.sql` to re-create the parent table -- with
--  a row per person whose device_id is their way-db username, verbatim and
--  case-sensitively. See AGENTS.md rule 19.
-- ============================================================
DROP TABLE IF EXISTS devices;

-- ============================================================
--  geofences: entry radius default changes 60m -> 50m (exit stays
--  entry + 40m = 90m). The seeded rows all inherited the old 60m DEFAULT,
--  so migrate them explicitly. New fences are created by the dashboard
--  with radius_m set explicitly, so the stale column DEFAULT no longer
--  matters.
-- ============================================================
UPDATE geofences SET radius_m = 50 WHERE radius_m = 60;
