#!/usr/bin/env node
/**
 * Data loader for the meeting-ETA lab (see 00-README.md).
 *
 * Writes `tracks.js` -- a plain `window.MEET_LAB_TRACKS = {...}` global -- so
 * `meet-lab.html` can be served with no CORS problem and no bundler (a
 * `fetch()` of a sibling file fails under file://, a <script src> does not).
 *
 * Two sources:
 *
 *   --demo                  (default) Synthesise five devices whose geometry is
 *                           known by construction. Exists so the lab is
 *                           verifiable without touching production data: every
 *                           scenario in it is one of the cases the design memo
 *                           argues about (a true head-on meet, a parallel road
 *                           that closes but never meets, a mover converging on
 *                           a parked peer, and a parked peer sitting inside a
 *                           geofence).
 *
 *   --source local|remote   Read real pings from way-db's `gps_pings`, which is
 *                           the historical record the fleet DO flushes nightly
 *                           from its buffers (see FleetDO's flush). `--remote`
 *                           reads PRODUCTION. It is a read-only SELECT, but it
 *                           is still production, hence the opt-in flag rather
 *                           than a default.
 *
 * The lab's whole point is eyeballing real trips, so `--source` is what you run
 * once the demo has convinced you the maths is wired right.
 *
 *   node scripts/one-off/2026-09-24-meet-eta-lab/build-data.mjs --demo
 *   node scripts/one-off/2026-09-24-meet-eta-lab/build-data.mjs --demo --minutes 2
 *   node scripts/one-off/2026-09-24-meet-eta-lab/build-data.mjs --source remote --days 3
 *   node scripts/one-off/2026-09-24-meet-eta-lab/build-data.mjs --source local --devices Niri,MaxX
 *
 * Read-only in every mode. There is nothing here that writes to a database.
 */
import { execFileSync } from "node:child_process";
import { writeFileSync } from "node:fs";
import { join, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const HERE = fileURLToPath(new URL(".", import.meta.url));
const REPO = resolve(HERE, "../../..");

// ── args ────────────────────────────────────────────────────────────────
const args = process.argv.slice(2);
const flag = (name, fallback = null) => {
  const i = args.indexOf(name);
  return i === -1 ? fallback : args[i + 1] ?? fallback;
};
const has = (name) => args.includes(name);

const source = has("--demo") || !flag("--source") ? "demo" : flag("--source");
if (!["demo", "local", "remote"].includes(source)) {
  console.error(`Unknown --source ${source} (expected demo | local | remote)`);
  process.exit(2);
}
const days = Number(flag("--days", "3"));
const devices = (flag("--devices") || "").split(",").map((s) => s.trim()).filter(Boolean);
const out = flag("--out", join(HERE, "tracks.js"));
const db = flag("--db", "WAY_DB");
const windowMin = Number(flag("--minutes", "10"));

if (devices.length && source === "demo") {
  console.error("--devices only applies to --source local|remote");
  process.exit(2);
}
if (has("--minutes") && source !== "demo") {
  console.error("--minutes only applies to the demo; real sources are windowed with --days");
  process.exit(2);
}
if (!Number.isFinite(windowMin) || windowMin < 0.5) {
  console.error(`--minutes must be a number >= 0.5 (got ${flag("--minutes")})`);
  process.exit(2);
}

// ── the shape meet-lab.html consumes ────────────────────────────────────
//
// One entry per reporter, pings ascending by `t` (ms since epoch). Names are
// deliberately short because they end up in table cells.
//
//   {t, lat, lon, kmh, driving, inside, fence, acc}
//
// `kmh` is the DEVICE's own speed report (metres/second * 3.6 at ingest, see
// way/routes/ingest.ts), NOT the ground truth the lab reconstructs from the
// fixes. Keeping both is the point: the lab derives its velocity vectors from
// consecutive fixes, and comparing that against the reported speed is how you
// notice a phone whose speed column lies.
function bundle({ source, devices, fences = [], notes = "" }) {
  return { generatedAt: new Date().toISOString(), source, devices, fences, notes };
}

function writeBundle(data) {
  const body = `// Generated by build-data.mjs at ${data.generatedAt} from source "${data.source}".\n// Regenerate rather than edit. Real data here is family location history.\nwindow.MEET_LAB_TRACKS = ${JSON.stringify(data)};\n`;
  writeFileSync(out, body);
  const pings = data.devices.reduce((n, d) => n + d.pings.length, 0);
  console.log(`wrote ${out}`);
  console.log(`  source   ${data.source}`);
  console.log(`  devices  ${data.devices.length} (${data.devices.map((d) => `${d.id}:${d.pings.length}`).join(", ")})`);
  console.log(`  pings    ${pings}`);
  if (data.devices.length < 2) console.log("  NOTE: fewer than 2 devices, so there are no pairs to compare.");
}

// ── demo source ─────────────────────────────────────────────────────────
//
// Antananarivo, because that is the app's timezone (UTC+3) and therefore the
// clock every timestamp in the real data is read against. Two north-south
// roads 473 m apart; 5 s cadence, 10 minutes by default (`--minutes 2` gives
// the 120 s cut of the same geometry -- see "A shorter window" in the README).
//
// The window is CUT, not compressed: the devices start where they start and
// drive at the speed they drive, so every minute of the short cut is identical
// to the same minute of the long one, and the head-on meet at t+95 s stays at
// t+95 s. The scenarios that live later than the cut (Aina's fence, the two
// teleports, Solo's gap) simply are not in it.
const ORIGIN = { lat: -18.9137, lon: 47.5361 };
const DEG = 180 / Math.PI;
const CADENCE_MS = 5000;
const MINUTES = windowMin;
const STEPS = Math.floor((MINUTES * 60000) / CADENCE_MS); // 120 at the default
/** The scenario steps below are authored against the full 10 minute run. */
const FULL_STEPS = (10 * 60000) / CADENCE_MS;
const ROAD_B_DEG = 0.0045; // ~473 m of longitude at this latitude
const NOISE_M = 6; // a phone with a decent fix
const M_PER_DEG_LAT = 110540;
const M_PER_DEG_LON = 111320 * Math.cos((ORIGIN.lat * Math.PI) / 180);

/** Deterministic PRNG so two runs of the demo produce identical numbers. */
function rng(seed) {
  let s = seed >>> 0;
  return () => {
    s = (s * 1664525 + 1013904223) >>> 0;
    return s / 4294967296;
  };
}
/** Box-Muller, so the noise is actually normal rather than uniform. */
function noise(r, sigma) {
  const u = Math.max(1e-9, r());
  return Math.sqrt(-2 * Math.log(u)) * Math.cos(2 * Math.PI * r()) * sigma;
}
function distanceM(lat1, lon1, lat2, lon2) {
  const dLat = (lat2 - lat1) * M_PER_DEG_LAT;
  const dLon = (lon2 - lon1) * M_PER_DEG_LON;
  return Math.hypot(dLat, dLon);
}

function buildDemo() {
  const start = Date.parse("2026-09-24T06:00:00Z");
  const pings = new Map();
  const push = (id, p) => {
    if (!pings.has(id)) pings.set(id, []);
    pings.get(id).push(p);
  };

  /**
   * A straight leg at a TRUE ground speed: each step advances kmh/3.6 * 5 s.
   * Deriving the endpoint from a fixed distance instead is what the first
   * draft did, and it made the demo report 40 km/h while crawling at 6 -- every
   * velocity the lab derives is then dominated by position noise, which is
   * exactly the failure this lab is supposed to expose, not commit.
   * headingDeg: 0 = north, 90 = east, 180 = south.
   */
  const leg = (id, dLat0, dLon0, headingDeg, kmh, opts = {}) => {
    const { teleport = [], gap = null, seed = 1 } = opts;
    // One stream PER SCENARIO, not one for the whole file: with a shared
    // stream, cutting the run short changes how many numbers every later leg
    // has drawn, so the 120 s cut stopped being a prefix of the 10 minute one.
    // Per-scenario seeds make the short window exactly the first minutes of
    // the long one, which is what makes them comparable.
    const r = rng(20260924 + seed);
    const stepM = (kmh / 3.6) * (CADENCE_MS / 1000);
    const dN = Math.cos(headingDeg / DEG) * stepM;
    const dE = Math.sin(headingDeg / DEG) * stepM;
    for (let i = 0; i <= STEPS; i++) {
      if (gap && i >= gap[0] && i <= gap[1]) continue; // no fix reported at all
      let jumpN = 0, jumpE = 0;
      for (const [at, northM, eastM] of teleport) {
        if (i !== at) continue;
        jumpN += northM; jumpE += eastM ?? 0;
      }
      const lat = ORIGIN.lat + dLat0 + (dN * i + jumpN) / M_PER_DEG_LAT + noise(r, NOISE_M) / M_PER_DEG_LAT;
      const lon = ORIGIN.lon + dLon0 + (dE * i + jumpE) / M_PER_DEG_LON + noise(r, NOISE_M) / M_PER_DEG_LON;
      push(id, {
        t: start + i * CADENCE_MS,
        lat: Number(lat.toFixed(6)),
        lon: Number(lon.toFixed(6)),
        kmh: Math.max(0, Number((kmh + noise(r, 1.6)).toFixed(1))),
        driving: kmh >= 15 ? 1 : 0,
        inside: 0,
        fence: null,
        acc: Number(Math.max(3, NOISE_M + 2 + noise(r, 2)).toFixed(1)),
      });
    }
  };

  // ── the scenarios ─────────────────────────────────────────────────────
  //
  // Niri comes south down Road A from 1.1 km north; MaxX comes north up Road A
  // from 1.1 km south. They pass at the origin at t+95 s -- the case the whole
  // concept is FOR. Niri also carries one 380 m teleport (mid-run, so it lands
  // among judged steps rather than at an edge).
  leg("Niri", 0.010, 0, 180, 40, { seed: 11, teleport: [[40, 380, 0]] });
  leg("MaxX", -0.010, 0, 0, 40, { seed: 22, teleport: [[30, -400, 0]] });

  // Kofi runs north up Road B, 473 m to the east, at the same 40 km/h. He and
  // MaxX stay 473 m apart the whole way (same direction, same speed: silent,
  // correctly). He and NIRI close head-on, both headings inside the 55 degree
  // gate, and still never meet -- the lateral offset IS the miss distance. That
  // pair is the row that proves a heading-only gate is not enough.
  leg("Kofi", -0.010, ROAD_B_DEG, 0, 40, { seed: 33 });

  // Solo comes north up Road A at 25 km/h, 30 m east of the centre line, so he
  // passes Aina (parked on the centre line) 30 m away. He is slower than MaxX
  // and starts 133 m behind him, so MaxX catches and overtakes him -- a pair
  // whose range closes while only ONE of them is pointed at the other, which is
  // what the heading gate exists to silence. Solo's run also has a 90 s hole in
  // it (no fixes at all): that is what the freshness gate is for.
  leg("Solo", -0.0112, 0.00028, 0, 25, { seed: 44, gap: [60, 77] });

  // Aina is parked on Road A inside the "Home" fence, so the bothOutside gate
  // hides her pairs even when the geometry is perfect. Flip that gate off in
  // the page and her rows appear -- the cost of the rule, made visible.
  const FENCE = { name: "Home1", display: "Home", lat: ORIGIN.lat + 0.004, lon: ORIGIN.lon, radiusM: 80, category: "Home" };
  const r = rng(20260924 + 55);
  for (let i = 0; i <= STEPS; i++) {
    push("Aina", {
      t: start + i * CADENCE_MS,
      lat: Number((FENCE.lat + noise(r, 4) / M_PER_DEG_LAT).toFixed(6)),
      lon: Number((FENCE.lon + noise(r, 4) / M_PER_DEG_LON).toFixed(6)),
      kmh: Number(Math.max(0, noise(r, 0.7)).toFixed(1)),
      driving: 0,
      inside: 1,
      fence: "Home1",
      acc: 6,
    });
  }

  // The fence flags are DERIVED, not authored: a ping is inside a fence when
  // its position says so, exactly as the app computes them. Doing it in a pass
  // over the finished tracks means Niri and MaxX are also correctly marked for
  // the few steps they spend driving past Aina's house.
  for (const list of pings.values()) {
    for (const p of list) {
      for (const f of [FENCE]) {
        const inFence = distanceM(p.lat, p.lon, f.lat, f.lon) <= f.radiusM;
        if (inFence) { p.inside = 1; p.fence = f.name; }
      }
    }
  }

  return bundle({
    source: "demo",
    devices: [...pings.entries()].map(([id, list]) => ({ id, pings: list })),
    fences: [FENCE],
    notes:
      `5 devices, ${Math.round((STEPS * CADENCE_MS) / 1000)} s at 5 s, Antananarivo. Ground truth by construction: Niri x MaxX pass at the origin at t+95 s (DCPA ~0); Niri x Kofi close head-on but pass 473 m apart; MaxX overtakes Solo; Solo converges on parked Aina, who sits inside a geofence. Niri carries a 380 m teleport and MaxX a 400 m one; Solo has a 90 s gap in his fixes.` +
      (STEPS < FULL_STEPS
        ? " This window is a CUT, not a compression: the scenarios that happen after it (Solo closing on Aina inside her fence, both teleports, Solo's 90 s gap) are not in it."
        : ""),
  });
}

// ── real sources ────────────────────────────────────────────────────────
function wranglerJson(sql, mode) {
  // Run wrangler's own entry point under this node rather than `npx`: on
  // Windows `execFileSync("npx.cmd", ...)` fails with EINVAL (a .cmd needs a
  // shell, and a shell reintroduces quoting problems). Passing the SQL as
  // `--command` keeps it a single argv element, so no shell quoting either.
  //
  // Do NOT go back to `--file` here: as of wrangler 4.133.0 that flag ingests
  // the file and returns a one-row "Total queries executed" SUMMARY instead of
  // the SELECT's rows, so this function silently reported zero pings -- the lab
  // rendered an empty map and it looked like the database was empty. (For a
  // migration, whose only point is the write, --file is still fine.)
  const wranglerJs = join(REPO, "node_modules", "wrangler", "bin", "wrangler.js");
  const stdout = execFileSync(
    process.execPath,
    [wranglerJs, "d1", "execute", db, `--${mode}`, "--json", `--command=${sql}`],
    { cwd: REPO, encoding: "utf8", maxBuffer: 256 * 1024 * 1024, stdio: ["ignore", "pipe", "inherit"] }
  );
  // Wrangler is chatty on stderr but the JSON body is the whole of stdout;
  // still, anchor rather than assume, because one --json change would otherwise
  // look like "no data" instead of "I could not parse the reply".
  const at = stdout.indexOf("[");
  if (at === -1) throw new Error(`wrangler did not return JSON:\n${stdout.slice(0, 800)}`);
  return JSON.parse(stdout.slice(at));
}

function buildFromDb(mode) {
  const since = new Date(Date.now() - days * 86400000).toISOString();
  const where = [`timestamp >= '${since}'`];
  if (devices.length) where.push(`device_id IN (${devices.map((d) => `'${d.replace(/'/g, "''")}'`).join(", ")})`);
  const rows = wranglerJson(
    `SELECT device_id, timestamp, latitude, longitude, speed, is_inside_geofence, geofence_name, is_driving, accuracy
       FROM gps_pings
      WHERE ${where.join(" AND ")}
      ORDER BY device_id ASC, timestamp ASC
      LIMIT 400000;`,
    mode
  );
  const geo = wranglerJson(`SELECT name, display_name, category, lat, lon, radius_m FROM geofences ORDER BY name;`, mode);

  const byDevice = new Map();
  for (const row of rows[0]?.results ?? []) {
    const t = Date.parse(row.timestamp);
    if (Number.isNaN(t)) continue;
    if (!byDevice.has(row.device_id)) byDevice.set(row.device_id, []);
    byDevice.get(row.device_id).push({
      t,
      lat: row.latitude,
      lon: row.longitude,
      kmh: row.speed === null || row.speed === undefined ? null : Number(row.speed),
      driving: row.is_driving ? 1 : 0,
      inside: row.is_inside_geofence ? 1 : 0,
      fence: row.geofence_name ?? null,
      acc: row.accuracy === null || row.accuracy === undefined ? null : Number(row.accuracy),
    });
  }

  return bundle({
    source: `${mode} (way-db gps_pings, last ${days} day(s))`,
    devices: [...byDevice.entries()]
      .map(([id, list]) => ({ id, pings: list.sort((a, b) => a.t - b.t) }))
      .sort((a, b) => b.pings.length - a.pings.length),
    fences: (geo[0]?.results ?? []).map((f) => ({
      name: f.name, display: f.display_name || f.name, lat: f.lat, lon: f.lon,
      radiusM: f.radius_m || 60, category: f.category ?? null,
    })),
    notes: `${mode} read of production way-db. gps_pings is flushed once a night at 21:00 UTC, so TODAY's tracks may be missing or short -- the fleet DO holds them until then.`,
  });
}

// ── go ──────────────────────────────────────────────────────────────────
try {
  writeBundle(source === "demo" ? buildDemo() : buildFromDb(source));
} catch (e) {
  console.error(`\n${e instanceof Error ? e.message : String(e)}`);
  process.exit(1);
}
